// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzYQqgRDG0uHQdA-WvDpHP9kddlWfIPB4',
    appId: '1:219140366426:web:97f01aeb9cc34f1a3ef863',
    messagingSenderId: '219140366426',
    projectId: 'tiktoke-saver',
    authDomain: 'tiktoke-saver.firebaseapp.com',
    storageBucket: 'tiktoke-saver.appspot.com',
    measurementId: 'G-WNGRKXEDJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2dUCUo0YmlC0go0MOkQeraZL7MFwysvE',
    appId: '1:219140366426:android:86bf66e2cc43db2d3ef863',
    messagingSenderId: '219140366426',
    projectId: 'tiktoke-saver',
    storageBucket: 'tiktoke-saver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNqk66uGPMBpo0sIc2glrlHppIg7URttk',
    appId: '1:219140366426:ios:43dbe2310d20a9b03ef863',
    messagingSenderId: '219140366426',
    projectId: 'tiktoke-saver',
    storageBucket: 'tiktoke-saver.appspot.com',
    iosBundleId: 'com.example.tiktokesaverproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNqk66uGPMBpo0sIc2glrlHppIg7URttk',
    appId: '1:219140366426:ios:6048c6d4fd7fbfc33ef863',
    messagingSenderId: '219140366426',
    projectId: 'tiktoke-saver',
    storageBucket: 'tiktoke-saver.appspot.com',
    iosBundleId: 'com.example.tiktokesaverproject.RunnerTests',
  );
}
